### ISSUE TITLE
Ethereum Holesky Support?

### ISSUE THREAD

**Issue by joe-dakota** [quiknode-labs/qn-oss#115]
Would it be possible to add Holesky support to the SDK?
```
/node_modules/@quicknode/sdk/esm/core/chains.js:57
    throw new QNChainNotSupported(endpointUrl);
          ^

QNChainNotSupported [Error]: The chain for endpoint URL https://THE_ENDPOINT is not currently supported by the QuickNode SDK.
```

Looking at the code, I think it was probably waiting on viem to add support:

https://github.com/quiknode-labs/qn-oss/blob/144504607be3a3970d29c3794f01e96b37d1d57e/packages/libs/sdk/src/core/chains.ts#L2-L24

Looks like it was introduced to viem around 4 months ago: https://github.com/wevm/viem/pull/1204

Thanks!

**Comment by johnpmitsch** [comment]
@joe-dakota thanks for the nudge! Added in 2.1.1 😄
